//! Encoder forward pass for wasm32+simd128 (BERT / XLM-R sentence encoders).
//! Model dims are compile-time constants generated by build.rs from
//! ../models.toml (select with PGT_MODEL). Batch of 1, no padding mask.
//! Weight layout must match pg_transformers/export.py.
#![no_std]
#![allow(static_mut_refs)]
use core::arch::wasm32::*;
use libm::{erff, expf, sqrtf};

// fused multiply-add when built with +relaxed-simd (feature-detect at load
// time and pick the kernel; V8 11.4+ supports it), else mul+add
#[inline(always)]
unsafe fn madd(a: v128, b: v128, acc: v128) -> v128 {
    #[cfg(target_feature = "relaxed-simd")]
    { f32x4_relaxed_madd(a, b, acc) }
    #[cfg(not(target_feature = "relaxed-simd"))]
    { f32x4_add(acc, f32x4_mul(a, b)) }
}

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    core::arch::wasm32::unreachable()
}

mod cfg {
    include!(concat!(env!("OUT_DIR"), "/cfg.rs"));
}
use cfg::*;

const DH: usize = H / HEADS;
const P: usize = MAXN + POS_OFFSET; // only the position rows we can ever index
const NWORD: usize = V * H;
const NREST: usize = P * H + H + 2 * H
    + L * (3 * (H * H + H) + (H * H + H) + 2 * H + (I * H + I) + (H * I + H) + 2 * H);

// Only the "rest" (positions + layers) is a static; it stays < 2GB (isize::MAX
// on wasm32). The word table (~1GB for bge-m3) is placed dynamically above the
// heap base by the JS loader, and its address is stored in WORD_BASE. Keeping
// both static would blow the wasm object-file's varint32 offset limit.
static mut W: [f32; NREST] = [0.0; NREST];
static mut WORD_BASE: usize = 0;
static mut IDS: [u32; MAXN] = [0; MAXN];
static mut X: [f32; MAXN * H] = [0.0; MAXN * H];
static mut Q: [f32; MAXN * H] = [0.0; MAXN * H];
static mut K: [f32; MAXN * H] = [0.0; MAXN * H];
static mut VA: [f32; MAXN * H] = [0.0; MAXN * H];
static mut ATT: [f32; MAXN * H] = [0.0; MAXN * H];
static mut PROJ: [f32; MAXN * H] = [0.0; MAXN * H];
static mut FFN1: [f32; MAXN * I] = [0.0; MAXN * I];
static mut SCORES: [f32; MAXN] = [0.0; MAXN];
static mut OUT: [f32; H] = [0.0; H];

#[no_mangle]
pub extern "C" fn rest_ptr() -> *mut f32 { unsafe { W.as_mut_ptr() } }
#[no_mangle]
pub extern "C" fn set_word_base(addr_bytes: u32) { unsafe { WORD_BASE = addr_bytes as usize; } }
#[no_mangle]
pub extern "C" fn n_word() -> i32 { NWORD as i32 }
#[no_mangle]
pub extern "C" fn n_rest() -> i32 { NREST as i32 }
#[no_mangle]
pub extern "C" fn ids_ptr() -> *mut u32 { unsafe { IDS.as_mut_ptr() } }
#[no_mangle]
pub extern "C" fn out_ptr() -> *const f32 { unsafe { OUT.as_ptr() } }
#[no_mangle]
pub extern "C" fn max_tokens() -> i32 { MAXN as i32 }
#[no_mangle]
pub extern "C" fn hidden() -> i32 { H as i32 }

#[inline(always)]
unsafe fn hsum(v: v128) -> f32 {
    f32x4_extract_lane::<0>(v) + f32x4_extract_lane::<1>(v)
        + f32x4_extract_lane::<2>(v) + f32x4_extract_lane::<3>(v)
}

/// SIMD dot product; k is a multiple of 16 for all supported dims.
#[inline]
unsafe fn dot(a: *const f32, b: *const f32, k: usize) -> f32 {
    let mut acc0 = f32x4_splat(0.0);
    let mut acc1 = f32x4_splat(0.0);
    let mut acc2 = f32x4_splat(0.0);
    let mut acc3 = f32x4_splat(0.0);
    let mut i = 0;
    while i < k {
        acc0 = madd(v128_load(a.add(i) as *const v128),
                    v128_load(b.add(i) as *const v128), acc0);
        acc1 = madd(v128_load(a.add(i + 4) as *const v128),
                    v128_load(b.add(i + 4) as *const v128), acc1);
        acc2 = madd(v128_load(a.add(i + 8) as *const v128),
                    v128_load(b.add(i + 8) as *const v128), acc2);
        acc3 = madd(v128_load(a.add(i + 12) as *const v128),
                    v128_load(b.add(i + 12) as *const v128), acc3);
        i += 16;
    }
    let s = f32x4_add(f32x4_add(acc0, acc1), f32x4_add(acc2, acc3));
    f32x4_extract_lane::<0>(s) + f32x4_extract_lane::<1>(s)
        + f32x4_extract_lane::<2>(s) + f32x4_extract_lane::<3>(s)
}

unsafe fn linear(x: *const f32, w_off: usize, b_off: usize, y: *mut f32,
                 n: usize, din: usize, dout: usize) {
    let wp = W.as_ptr().add(w_off);
    let bp = W.as_ptr().add(b_off);
    // register-block 4 tokens per weight row: the kernel is load-bandwidth
    // bound (2 loads per madd), so amortizing each weight load over 4 tokens
    // cuts weight traffic 4x; the 4 accumulator chains also add ILP.
    for j in 0..dout {
        let wj = wp.add(j * din);
        let bj = *bp.add(j);
        let mut t = 0;
        while t + 4 <= n {
            let (x0, x1, x2, x3) = (x.add(t * din), x.add((t + 1) * din),
                                    x.add((t + 2) * din), x.add((t + 3) * din));
            let mut a0 = f32x4_splat(0.0);
            let mut a1 = f32x4_splat(0.0);
            let mut a2 = f32x4_splat(0.0);
            let mut a3 = f32x4_splat(0.0);
            let mut i = 0;
            while i < din {
                let wv = v128_load(wj.add(i) as *const v128);
                a0 = madd(wv, v128_load(x0.add(i) as *const v128), a0);
                a1 = madd(wv, v128_load(x1.add(i) as *const v128), a1);
                a2 = madd(wv, v128_load(x2.add(i) as *const v128), a2);
                a3 = madd(wv, v128_load(x3.add(i) as *const v128), a3);
                i += 4;
            }
            *y.add(t * dout + j) = bj + hsum(a0);
            *y.add((t + 1) * dout + j) = bj + hsum(a1);
            *y.add((t + 2) * dout + j) = bj + hsum(a2);
            *y.add((t + 3) * dout + j) = bj + hsum(a3);
            t += 4;
        }
        while t < n {
            *y.add(t * dout + j) = bj + dot(x.add(t * din), wj, din);
            t += 1;
        }
    }
}

unsafe fn ln_row(row: *mut f32, g_off: usize, b_off: usize) {
    let mut m = 0.0f32;
    for d in 0..H { m += *row.add(d); }
    m /= H as f32;
    let mut v = 0.0f32;
    for d in 0..H { let z = *row.add(d) - m; v += z * z; }
    v /= H as f32;
    let inv = 1.0 / sqrtf(v + LN_EPS);
    for d in 0..H {
        *row.add(d) = (*row.add(d) - m) * inv * W[g_off + d] + W[b_off + d];
    }
}

unsafe fn add_residual_ln(res: *mut f32, g_off: usize, b_off: usize, n: usize) {
    for t in 0..n {
        let xr = res.add(t * H);
        let pr = PROJ.as_ptr().add(t * H);
        for d in 0..H { *xr.add(d) += *pr.add(d); }
        ln_row(xr, g_off, b_off);
    }
}

unsafe fn attention(n: usize) {
    let scale = 1.0 / sqrtf(DH as f32);
    for h in 0..HEADS {
        let ho = h * DH;
        for t in 0..n {
            let qp = Q.as_ptr().add(t * H + ho);
            let mut mx = f32::NEG_INFINITY;
            for s in 0..n {
                let v = dot(qp, K.as_ptr().add(s * H + ho), DH) * scale;
                SCORES[s] = v;
                if v > mx { mx = v; }
            }
            let mut sum = 0.0f32;
            for s in 0..n {
                let e = expf(SCORES[s] - mx);
                SCORES[s] = e;
                sum += e;
            }
            let inv = 1.0 / sum;
            let mut acc = [f32x4_splat(0.0); DH / 4];
            for s in 0..n {
                let p = f32x4_splat(SCORES[s] * inv);
                let vp = VA.as_ptr().add(s * H + ho);
                for j in 0..DH / 4 {
                    acc[j] = madd(p, v128_load(vp.add(4 * j) as *const v128), acc[j]);
                }
            }
            let ap = ATT.as_mut_ptr().add(t * H + ho);
            for j in 0..DH / 4 {
                v128_store(ap.add(4 * j) as *mut v128, acc[j]);
            }
        }
    }
}

#[inline]
fn gelu(x: f32) -> f32 {
    0.5 * x * (1.0 + erff(x * core::f32::consts::FRAC_1_SQRT_2))
}

struct Cur(usize);
impl Cur {
    fn take(&mut self, n: usize) -> usize { let o = self.0; self.0 += n; o }
}

#[no_mangle]
pub extern "C" fn forward(n_tokens: i32) {
    unsafe {
        let n = (n_tokens as usize).min(MAXN);
        if n == 0 {
            for d in 0..H { OUT[d] = 0.0; }
            return;
        }
        let mut c = Cur(0); // cursor into the rest region; word table is separate
        let pos = c.take(P * H);
        let typ = c.take(H);
        let eg = c.take(H);
        let eb = c.take(H);

        let word = WORD_BASE as *const f32;
        for t in 0..n {
            let id = (IDS[t] as usize).min(V - 1);
            let xr = X.as_mut_ptr().add(t * H);
            for d in 0..H {
                *xr.add(d) = *word.add(id * H + d)
                    + W[pos + (t + POS_OFFSET) * H + d]
                    + W[typ + d];
            }
            ln_row(xr, eg, eb);
        }

        for _l in 0..L {
            let qw = c.take(H * H); let qb = c.take(H);
            let kw = c.take(H * H); let kb = c.take(H);
            let vw = c.take(H * H); let vb = c.take(H);
            let aow = c.take(H * H); let aob = c.take(H);
            let ag = c.take(H); let ab = c.take(H);
            let fiw = c.take(I * H); let fib = c.take(I);
            let fow = c.take(H * I); let fob = c.take(H);
            let fg = c.take(H); let fb = c.take(H);

            linear(X.as_ptr(), qw, qb, Q.as_mut_ptr(), n, H, H);
            linear(X.as_ptr(), kw, kb, K.as_mut_ptr(), n, H, H);
            linear(X.as_ptr(), vw, vb, VA.as_mut_ptr(), n, H, H);
            attention(n);
            linear(ATT.as_ptr(), aow, aob, PROJ.as_mut_ptr(), n, H, H);
            add_residual_ln(X.as_mut_ptr(), ag, ab, n);

            linear(X.as_ptr(), fiw, fib, FFN1.as_mut_ptr(), n, H, I);
            for i in 0..n * I { FFN1[i] = gelu(FFN1[i]); }
            linear(FFN1.as_ptr(), fow, fob, PROJ.as_mut_ptr(), n, I, H);
            add_residual_ln(X.as_mut_ptr(), fg, fb, n);
        }

        // pool + L2 normalize
        for d in 0..H { OUT[d] = 0.0; }
        if POOL_CLS {
            for d in 0..H { OUT[d] = X[d]; }
        } else {
            for t in 0..n {
                for d in 0..H { OUT[d] += X[t * H + d]; }
            }
            let invn = 1.0 / n as f32;
            for d in 0..H { OUT[d] *= invn; }
        }
        let mut norm = 0.0f32;
        for d in 0..H { norm += OUT[d] * OUT[d]; }
        let inv = 1.0 / sqrtf(norm.max(1e-24));
        for d in 0..H { OUT[d] *= inv; }
    }
}
