//! Encoder forward pass for wasm32+simd128 (BERT / XLM-R sentence encoders).
//! Model dims are compile-time constants generated by build.rs from
//! ../models.toml (select with PGT_MODEL). Batch of 1, no padding mask.
//! Weight layout must match pg_transformers/export.py.
#![no_std]
#![allow(static_mut_refs)]
use core::arch::wasm32::*;
use libm::{erff, expf, sqrtf};

// fused multiply-add when built with +relaxed-simd (feature-detect at load
// time and pick the kernel; V8 11.4+ supports it), else mul+add
#[inline(always)]
unsafe fn madd(a: v128, b: v128, acc: v128) -> v128 {
    #[cfg(target_feature = "relaxed-simd")]
    { f32x4_relaxed_madd(a, b, acc) }
    #[cfg(not(target_feature = "relaxed-simd"))]
    { f32x4_add(acc, f32x4_mul(a, b)) }
}

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    core::arch::wasm32::unreachable()
}

mod cfg {
    include!(concat!(env!("OUT_DIR"), "/cfg.rs"));
}
use cfg::*;

const DH: usize = H / HEADS;
const P: usize = MAXN + POS_OFFSET; // only the position rows we can ever index
const NWORD: usize = V * H;
// f32 elements in the static rest region. The int8 layout keeps positions,
// type, LayerNorm params, biases and per-row scales (one per output row,
// plus one per vocab row for the word table) in f32; the linear weights
// themselves move to the QW int8 region.
const NREST: usize = if QUANT_INT8 {
    P * H + H + 2 * H + V + L * (14 * H + 2 * I)
} else {
    P * H + H + 2 * H
        + L * (3 * (H * H + H) + (H * H + H) + 2 * H + (I * H + I) + (H * I + H) + 2 * H)
};
// int8 linear weights, bytes (empty for fp32 models)
const NQW: usize = if QUANT_INT8 { L * (4 * H * H + 2 * I * H) } else { 0 };
const WORD_BYTES: usize = NWORD * (if QUANT_INT8 { 1 } else { 4 });

// Only the "rest" (positions + layers) is a static; it stays < 2GB (isize::MAX
// on wasm32). The word table (~1GB for bge-m3) is placed dynamically above the
// heap base by the JS loader, and its address is stored in WORD_BASE. Keeping
// both static would blow the wasm object-file's varint32 offset limit.
static mut W: [f32; NREST] = [0.0; NREST];
#[repr(align(16))]
struct QAligned([i8; NQW]);
static mut QW: QAligned = QAligned([0; NQW]);
static mut WORD_BASE: usize = 0;
static mut IDS: [u32; MAXN] = [0; MAXN];
static mut X: [f32; MAXN * H] = [0.0; MAXN * H];
static mut Q: [f32; MAXN * H] = [0.0; MAXN * H];
static mut K: [f32; MAXN * H] = [0.0; MAXN * H];
static mut VA: [f32; MAXN * H] = [0.0; MAXN * H];
static mut ATT: [f32; MAXN * H] = [0.0; MAXN * H];
static mut PROJ: [f32; MAXN * H] = [0.0; MAXN * H];
static mut FFN1: [f32; MAXN * I] = [0.0; MAXN * I];
static mut SCORES: [f32; MAXN] = [0.0; MAXN];
static mut OUT: [f32; H] = [0.0; H];

// int8 builds quantize the input rows of every linear to asymmetric u8
// scratch (x ~ scale*xq + xmin) with one scale/min per BQ-column block per
// token - per-token ranges are inflated by transformer outlier channels
// (visible as a cosine drop on the 24-layer bge-m3), per-block ranges are
// not. The GEMM then runs in the integer domain: i32x4.dot_i16x8_s on
// baseline SIMD, or the relaxed i8 dot (SDOT/VNNI) with +relaxed-simd. The
// relaxed instruction only guarantees portable results when its second
// operand is 7-bit, so that path splits each u8 activation as
// a = 2*(a>>1) + (a&1) and chains three dots (hi, hi, lo) - exact u8
// reconstruction, both halves in [0,127].
const QIN: usize = if QUANT_INT8 { if I > H { I } else { H } } else { 0 };
const BQ: usize = 128; // every H and I is a multiple of this
const MAXNB: usize = QIN / BQ;
const NASC: usize = if QUANT_INT8 { MAXN * MAXNB } else { 0 };
// one weight-row sum per BQ-block per linear output row, in QW layout
// order; filled by prep() after the weights stream in, used to fold the
// activation offset back in per block:
// sum_i(w*x) = sum_b(ascale_b*dot(wq_b,xq_b) + xmin_b*rowsum_b)
const NROWS: usize = if QUANT_INT8 {
    L * (4 * H * (H / BQ) + I * (H / BQ) + H * (I / BQ))
} else { 0 };
const QMAXF: f32 = 255.0;
#[repr(align(16))]
struct XqAligned([u8; MAXN * QIN]);
static mut XQ: XqAligned = XqAligned([0; MAXN * QIN]);
static mut ASCALE: [f32; NASC] = [0.0; NASC];
static mut AMIN: [f32; NASC] = [0.0; NASC];
static mut RSUM: [f32; NROWS] = [0.0; NROWS];

#[no_mangle]
pub extern "C" fn rest_ptr() -> *mut f32 { unsafe { W.as_mut_ptr() } }
#[no_mangle]
pub extern "C" fn qw_ptr() -> *mut i8 { unsafe { QW.0.as_mut_ptr() } }
#[no_mangle]
pub extern "C" fn set_word_base(addr_bytes: u32) { unsafe { WORD_BASE = addr_bytes as usize; } }
#[no_mangle]
pub extern "C" fn n_word_bytes() -> i32 { WORD_BYTES as i32 }
#[no_mangle]
pub extern "C" fn n_rest_bytes() -> i32 { (NREST * 4) as i32 }
#[no_mangle]
pub extern "C" fn n_qw_bytes() -> i32 { NQW as i32 }
#[no_mangle]
pub extern "C" fn ids_ptr() -> *mut u32 { unsafe { IDS.as_mut_ptr() } }
#[no_mangle]
pub extern "C" fn out_ptr() -> *const f32 { unsafe { OUT.as_ptr() } }
#[no_mangle]
pub extern "C" fn max_tokens() -> i32 { MAXN as i32 }
#[no_mangle]
pub extern "C" fn hidden() -> i32 { H as i32 }

/// sum each BQ-block of each int8 weight row into RSUM (exact small ints)
unsafe fn sum_rows(w_off: usize, r_off: usize, rows: usize, din: usize) {
    let nb = din / BQ;
    for j in 0..rows {
        let wj = QW.0.as_ptr().add(w_off + j * din);
        for b in 0..nb {
            let mut acc = i32x4_splat(0);
            let mut i = b * BQ;
            while i < (b + 1) * BQ {
                acc = i32x4_add(acc, i32x4_extadd_pairwise_i16x8(
                    i16x8_extadd_pairwise_i8x16(v128_load(wj.add(i) as *const v128))));
                i += 16;
            }
            *RSUM.as_mut_ptr().add(r_off + j * nb + b) = hsum_i32(acc) as f32;
        }
    }
}

/// int8 builds: precompute per-row per-block weight sums (one pass over
/// QW). The JS loader calls this once after the weights finish streaming.
#[no_mangle]
pub extern "C" fn prep() {
    if !QUANT_INT8 { return; }
    unsafe {
        let mut cq = Cur(0);
        let mut cr = Cur(0);
        for _l in 0..L {
            sum_rows(cq.take(H * H), cr.take(H * (H / BQ)), H, H);
            sum_rows(cq.take(H * H), cr.take(H * (H / BQ)), H, H);
            sum_rows(cq.take(H * H), cr.take(H * (H / BQ)), H, H);
            sum_rows(cq.take(H * H), cr.take(H * (H / BQ)), H, H);
            sum_rows(cq.take(I * H), cr.take(I * (H / BQ)), I, H);
            sum_rows(cq.take(H * I), cr.take(H * (I / BQ)), H, I);
        }
    }
}

#[inline(always)]
unsafe fn hsum(v: v128) -> f32 {
    f32x4_extract_lane::<0>(v) + f32x4_extract_lane::<1>(v)
        + f32x4_extract_lane::<2>(v) + f32x4_extract_lane::<3>(v)
}

/// SIMD dot product; k is a multiple of 16 for all supported dims.
#[inline]
unsafe fn dot(a: *const f32, b: *const f32, k: usize) -> f32 {
    let mut acc0 = f32x4_splat(0.0);
    let mut acc1 = f32x4_splat(0.0);
    let mut acc2 = f32x4_splat(0.0);
    let mut acc3 = f32x4_splat(0.0);
    let mut i = 0;
    while i < k {
        acc0 = madd(v128_load(a.add(i) as *const v128),
                    v128_load(b.add(i) as *const v128), acc0);
        acc1 = madd(v128_load(a.add(i + 4) as *const v128),
                    v128_load(b.add(i + 4) as *const v128), acc1);
        acc2 = madd(v128_load(a.add(i + 8) as *const v128),
                    v128_load(b.add(i + 8) as *const v128), acc2);
        acc3 = madd(v128_load(a.add(i + 12) as *const v128),
                    v128_load(b.add(i + 12) as *const v128), acc3);
        i += 16;
    }
    let s = f32x4_add(f32x4_add(acc0, acc1), f32x4_add(acc2, acc3));
    f32x4_extract_lane::<0>(s) + f32x4_extract_lane::<1>(s)
        + f32x4_extract_lane::<2>(s) + f32x4_extract_lane::<3>(s)
}

unsafe fn linear(x: *const f32, w_off: usize, b_off: usize, y: *mut f32,
                 n: usize, din: usize, dout: usize) {
    let wp = W.as_ptr().add(w_off);
    let bp = W.as_ptr().add(b_off);
    // register-block 2 output rows x 4 tokens: each weight load is reused
    // across 4 tokens and each activation load across 2 rows (0.75 loads per
    // madd vs 2 unblocked) - the kernel is bound by loads, not compute. Each
    // (row,token) pair accumulates in its own single chain, in weight order,
    // so results do not depend on the blocking.
    let mut j = 0;
    while j + 2 <= dout {
        let wj0 = wp.add(j * din);
        let wj1 = wp.add((j + 1) * din);
        let (bj0, bj1) = (*bp.add(j), *bp.add(j + 1));
        let mut t = 0;
        while t + 4 <= n {
            let (x0, x1, x2, x3) = (x.add(t * din), x.add((t + 1) * din),
                                    x.add((t + 2) * din), x.add((t + 3) * din));
            let mut a00 = f32x4_splat(0.0); let mut a01 = f32x4_splat(0.0);
            let mut a10 = f32x4_splat(0.0); let mut a11 = f32x4_splat(0.0);
            let mut a20 = f32x4_splat(0.0); let mut a21 = f32x4_splat(0.0);
            let mut a30 = f32x4_splat(0.0); let mut a31 = f32x4_splat(0.0);
            let mut i = 0;
            while i < din {
                let w0 = v128_load(wj0.add(i) as *const v128);
                let w1 = v128_load(wj1.add(i) as *const v128);
                let mut xv;
                xv = v128_load(x0.add(i) as *const v128);
                a00 = madd(w0, xv, a00); a01 = madd(w1, xv, a01);
                xv = v128_load(x1.add(i) as *const v128);
                a10 = madd(w0, xv, a10); a11 = madd(w1, xv, a11);
                xv = v128_load(x2.add(i) as *const v128);
                a20 = madd(w0, xv, a20); a21 = madd(w1, xv, a21);
                xv = v128_load(x3.add(i) as *const v128);
                a30 = madd(w0, xv, a30); a31 = madd(w1, xv, a31);
                i += 4;
            }
            *y.add(t * dout + j) = bj0 + hsum(a00);
            *y.add(t * dout + j + 1) = bj1 + hsum(a01);
            *y.add((t + 1) * dout + j) = bj0 + hsum(a10);
            *y.add((t + 1) * dout + j + 1) = bj1 + hsum(a11);
            *y.add((t + 2) * dout + j) = bj0 + hsum(a20);
            *y.add((t + 2) * dout + j + 1) = bj1 + hsum(a21);
            *y.add((t + 3) * dout + j) = bj0 + hsum(a30);
            *y.add((t + 3) * dout + j + 1) = bj1 + hsum(a31);
            t += 4;
        }
        while t < n {
            *y.add(t * dout + j) = bj0 + dot(x.add(t * din), wj0, din);
            *y.add(t * dout + j + 1) = bj1 + dot(x.add(t * din), wj1, din);
            t += 1;
        }
        j += 2;
    }
    while j < dout {
        // dout is a multiple of 16 for every registered model; kept for safety
        let wj = wp.add(j * din);
        let bj = *bp.add(j);
        for t in 0..n {
            *y.add(t * dout + j) = bj + dot(x.add(t * din), wj, din);
        }
        j += 1;
    }
}

#[inline(always)]
unsafe fn hsum_i32(v: v128) -> i32 {
    i32x4_extract_lane::<0>(v) + i32x4_extract_lane::<1>(v)
        + i32x4_extract_lane::<2>(v) + i32x4_extract_lane::<3>(v)
}

/// Quantize n rows of k f32 (k a multiple of BQ) to asymmetric u8 in XQ,
/// one scale/min per BQ-column block: xq = round((x - xmin_b) * QMAXF /
/// (xmax_b - xmin_b)), so x ~ ASCALE[t*nb+b]*xq + AMIN[t*nb+b].
/// round-to-nearest-even, saturating narrow.
unsafe fn quant_rows(x: *const f32, n: usize, k: usize) {
    let nb = k / BQ;
    for t in 0..n {
        for b in 0..nb {
            let xr = x.add(t * k + b * BQ);
            let mut mn = v128_load(xr as *const v128);
            let mut mx = mn;
            let mut i = 4;
            while i < BQ {
                let v = v128_load(xr.add(i) as *const v128);
                mn = f32x4_pmin(mn, v);
                mx = f32x4_pmax(mx, v);
                i += 4;
            }
            let xmin = f32x4_extract_lane::<0>(mn)
                .min(f32x4_extract_lane::<1>(mn))
                .min(f32x4_extract_lane::<2>(mn))
                .min(f32x4_extract_lane::<3>(mn));
            let xmax = f32x4_extract_lane::<0>(mx)
                .max(f32x4_extract_lane::<1>(mx))
                .max(f32x4_extract_lane::<2>(mx))
                .max(f32x4_extract_lane::<3>(mx));
            let range = xmax - xmin;
            let (scale, inv) =
                if range > 0.0 { (range / QMAXF, QMAXF / range) } else { (1.0, 0.0) };
            *ASCALE.as_mut_ptr().add(t * nb + b) = scale;
            *AMIN.as_mut_ptr().add(t * nb + b) = xmin;
            let iv = f32x4_splat(inv);
            let mv = f32x4_splat(xmin);
            let out = XQ.0.as_mut_ptr().add(t * k + b * BQ);
            let mut i = 0;
            while i < BQ {
                let q = |o: usize| i32x4_trunc_sat_f32x4(f32x4_nearest(f32x4_mul(
                    f32x4_sub(v128_load(xr.add(i + o) as *const v128), mv), iv)));
                let lo = i16x8_narrow_i32x4(q(0), q(4));
                let hi = i16x8_narrow_i32x4(q(8), q(12));
                v128_store(out.add(i) as *mut v128, u8x16_narrow_i16x8(lo, hi));
                i += 16;
            }
        }
    }
}

/// one BQ-block of the u8-activation x int8-weight dot product, in the
/// integer domain. The caller applies the block scale and offset.
#[inline]
unsafe fn dot_q8_blk(a: *const u8, w: *const i8) -> i32 {
    #[cfg(target_feature = "relaxed-simd")]
    {
        let one = u8x16_splat(1);
        let mut acc = i32x4_splat(0);
        let mut i = 0;
        while i < BQ {
            let wv = v128_load(w.add(i) as *const v128);
            let av = v128_load(a.add(i) as *const v128);
            let ahi = u8x16_shr(av, 1);
            let alo = v128_and(av, one);
            acc = i32x4_relaxed_dot_i8x16_i7x16_add(wv, ahi, acc);
            acc = i32x4_relaxed_dot_i8x16_i7x16_add(wv, ahi, acc);
            acc = i32x4_relaxed_dot_i8x16_i7x16_add(wv, alo, acc);
            i += 16;
        }
        hsum_i32(acc)
    }
    #[cfg(not(target_feature = "relaxed-simd"))]
    {
        let mut acc0 = i32x4_splat(0);
        let mut acc1 = i32x4_splat(0);
        let mut i = 0;
        while i < BQ {
            let av = v128_load(a.add(i) as *const v128);
            let wv = v128_load(w.add(i) as *const v128);
            acc0 = i32x4_add(acc0, i32x4_dot_i16x8(
                u16x8_extend_low_u8x16(av), i16x8_extend_low_i8x16(wv)));
            acc1 = i32x4_add(acc1, i32x4_dot_i16x8(
                u16x8_extend_high_u8x16(av), i16x8_extend_high_i8x16(wv)));
            i += 16;
        }
        hsum_i32(i32x4_add(acc0, acc1))
    }
}

/// full-row dot for the tail paths: sum over blocks of
/// ascale_b*dot(wq_b,xq_b) + xmin_b*rowsum_b
#[inline]
unsafe fn dot_q8(a: *const u8, w: *const i8, cs: *const f32, cm: *const f32,
                 rs: *const f32, nb: usize) -> f32 {
    let mut y = 0.0f32;
    for b in 0..nb {
        y += *cs.add(b) * dot_q8_blk(a.add(b * BQ), w.add(b * BQ)) as f32
            + *cm.add(b) * *rs.add(b);
    }
    y
}

/// weight-only int8 linear over per-token per-block u8 activations (call
/// quant_rows on the f32 input first; reads XQ/ASCALE/AMIN). Weight rows
/// live in QW as int8, W holds one f32 scale per output row (s_off) and the
/// bias (b_off); RSUM (from rs_off, filled by prep) folds the activation
/// offsets back in: y = b + wscale * sum_b(ascale_b*dot(wq_b,xq_b) +
/// xmin_b*rowsum_b). Each block's integer dot runs in the integer domain -
/// i32x4.dot_i16x8_s on baseline SIMD, the relaxed i8 dot (SDOT/VNNI, 16
/// madds per instruction) with +relaxed-simd - and is folded into f32x4
/// accumulators with one convert+madd per block. Register-blocks 2 output
/// rows x 4 tokens as in linear(). Integer accumulation is associative and
/// the f32 fold happens once per block in block order, so results do not
/// depend on the register blocking.
unsafe fn linear_q8(w_off: usize, rs_off: usize, s_off: usize, b_off: usize,
                    y: *mut f32, n: usize, din: usize, dout: usize) {
    let nb = din / BQ;
    let xq = XQ.0.as_ptr();
    let asc = ASCALE.as_ptr();
    let amn = AMIN.as_ptr();
    let wp = QW.0.as_ptr().add(w_off);
    let rp = RSUM.as_ptr().add(rs_off);
    let sp = W.as_ptr().add(s_off);
    let bp = W.as_ptr().add(b_off);
    // xmin_b * rowsum_b summed over blocks, one token row against one
    // weight row: a tiny nb-long dot product
    #[inline(always)]
    unsafe fn mincorr(cm: *const f32, rs: *const f32, nb: usize) -> f32 {
        let mut s = 0.0f32;
        for b in 0..nb { s += *cm.add(b) * *rs.add(b); }
        s
    }
    let mut j = 0;
    while j + 2 <= dout {
        let wj0 = wp.add(j * din);
        let wj1 = wp.add((j + 1) * din);
        let (sj0, sj1) = (*sp.add(j), *sp.add(j + 1));
        let (bj0, bj1) = (*bp.add(j), *bp.add(j + 1));
        let (rj0, rj1) = (rp.add(j * nb), rp.add((j + 1) * nb));
        let mut t = 0;
        while t + 4 <= n {
            let (x0, x1, x2, x3) = (xq.add(t * din), xq.add((t + 1) * din),
                                    xq.add((t + 2) * din), xq.add((t + 3) * din));
            let mut y00 = f32x4_splat(0.0); let mut y01 = f32x4_splat(0.0);
            let mut y10 = f32x4_splat(0.0); let mut y11 = f32x4_splat(0.0);
            let mut y20 = f32x4_splat(0.0); let mut y21 = f32x4_splat(0.0);
            let mut y30 = f32x4_splat(0.0); let mut y31 = f32x4_splat(0.0);
            for b in 0..nb {
                let mut a00 = i32x4_splat(0); let mut a01 = i32x4_splat(0);
                let mut a10 = i32x4_splat(0); let mut a11 = i32x4_splat(0);
                let mut a20 = i32x4_splat(0); let mut a21 = i32x4_splat(0);
                let mut a30 = i32x4_splat(0); let mut a31 = i32x4_splat(0);
                let mut i = b * BQ;
                while i < (b + 1) * BQ {
                    let w0v = v128_load(wj0.add(i) as *const v128);
                    let w1v = v128_load(wj1.add(i) as *const v128);
                    #[cfg(target_feature = "relaxed-simd")]
                    {
                        let one = u8x16_splat(1);
                        let mut av; let mut ahi; let mut alo;
                        av = v128_load(x0.add(i) as *const v128);
                        ahi = u8x16_shr(av, 1); alo = v128_and(av, one);
                        a00 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, ahi, a00);
                        a00 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, ahi, a00);
                        a00 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, alo, a00);
                        a01 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, ahi, a01);
                        a01 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, ahi, a01);
                        a01 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, alo, a01);
                        av = v128_load(x1.add(i) as *const v128);
                        ahi = u8x16_shr(av, 1); alo = v128_and(av, one);
                        a10 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, ahi, a10);
                        a10 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, ahi, a10);
                        a10 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, alo, a10);
                        a11 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, ahi, a11);
                        a11 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, ahi, a11);
                        a11 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, alo, a11);
                        av = v128_load(x2.add(i) as *const v128);
                        ahi = u8x16_shr(av, 1); alo = v128_and(av, one);
                        a20 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, ahi, a20);
                        a20 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, ahi, a20);
                        a20 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, alo, a20);
                        a21 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, ahi, a21);
                        a21 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, ahi, a21);
                        a21 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, alo, a21);
                        av = v128_load(x3.add(i) as *const v128);
                        ahi = u8x16_shr(av, 1); alo = v128_and(av, one);
                        a30 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, ahi, a30);
                        a30 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, ahi, a30);
                        a30 = i32x4_relaxed_dot_i8x16_i7x16_add(w0v, alo, a30);
                        a31 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, ahi, a31);
                        a31 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, ahi, a31);
                        a31 = i32x4_relaxed_dot_i8x16_i7x16_add(w1v, alo, a31);
                    }
                    #[cfg(not(target_feature = "relaxed-simd"))]
                    {
                        let w0l = i16x8_extend_low_i8x16(w0v);
                        let w0h = i16x8_extend_high_i8x16(w0v);
                        let w1l = i16x8_extend_low_i8x16(w1v);
                        let w1h = i16x8_extend_high_i8x16(w1v);
                        let mut av; let mut al; let mut ah;
                        av = v128_load(x0.add(i) as *const v128);
                        al = u16x8_extend_low_u8x16(av); ah = u16x8_extend_high_u8x16(av);
                        a00 = i32x4_add(a00, i32x4_dot_i16x8(al, w0l));
                        a00 = i32x4_add(a00, i32x4_dot_i16x8(ah, w0h));
                        a01 = i32x4_add(a01, i32x4_dot_i16x8(al, w1l));
                        a01 = i32x4_add(a01, i32x4_dot_i16x8(ah, w1h));
                        av = v128_load(x1.add(i) as *const v128);
                        al = u16x8_extend_low_u8x16(av); ah = u16x8_extend_high_u8x16(av);
                        a10 = i32x4_add(a10, i32x4_dot_i16x8(al, w0l));
                        a10 = i32x4_add(a10, i32x4_dot_i16x8(ah, w0h));
                        a11 = i32x4_add(a11, i32x4_dot_i16x8(al, w1l));
                        a11 = i32x4_add(a11, i32x4_dot_i16x8(ah, w1h));
                        av = v128_load(x2.add(i) as *const v128);
                        al = u16x8_extend_low_u8x16(av); ah = u16x8_extend_high_u8x16(av);
                        a20 = i32x4_add(a20, i32x4_dot_i16x8(al, w0l));
                        a20 = i32x4_add(a20, i32x4_dot_i16x8(ah, w0h));
                        a21 = i32x4_add(a21, i32x4_dot_i16x8(al, w1l));
                        a21 = i32x4_add(a21, i32x4_dot_i16x8(ah, w1h));
                        av = v128_load(x3.add(i) as *const v128);
                        al = u16x8_extend_low_u8x16(av); ah = u16x8_extend_high_u8x16(av);
                        a30 = i32x4_add(a30, i32x4_dot_i16x8(al, w0l));
                        a30 = i32x4_add(a30, i32x4_dot_i16x8(ah, w0h));
                        a31 = i32x4_add(a31, i32x4_dot_i16x8(al, w1l));
                        a31 = i32x4_add(a31, i32x4_dot_i16x8(ah, w1h));
                    }
                    i += 16;
                }
                let cs0 = f32x4_splat(*asc.add(t * nb + b));
                let cs1 = f32x4_splat(*asc.add((t + 1) * nb + b));
                let cs2 = f32x4_splat(*asc.add((t + 2) * nb + b));
                let cs3 = f32x4_splat(*asc.add((t + 3) * nb + b));
                y00 = madd(f32x4_convert_i32x4(a00), cs0, y00);
                y01 = madd(f32x4_convert_i32x4(a01), cs0, y01);
                y10 = madd(f32x4_convert_i32x4(a10), cs1, y10);
                y11 = madd(f32x4_convert_i32x4(a11), cs1, y11);
                y20 = madd(f32x4_convert_i32x4(a20), cs2, y20);
                y21 = madd(f32x4_convert_i32x4(a21), cs2, y21);
                y30 = madd(f32x4_convert_i32x4(a30), cs3, y30);
                y31 = madd(f32x4_convert_i32x4(a31), cs3, y31);
            }
            *y.add(t * dout + j) =
                bj0 + sj0 * (hsum(y00) + mincorr(amn.add(t * nb), rj0, nb));
            *y.add(t * dout + j + 1) =
                bj1 + sj1 * (hsum(y01) + mincorr(amn.add(t * nb), rj1, nb));
            *y.add((t + 1) * dout + j) =
                bj0 + sj0 * (hsum(y10) + mincorr(amn.add((t + 1) * nb), rj0, nb));
            *y.add((t + 1) * dout + j + 1) =
                bj1 + sj1 * (hsum(y11) + mincorr(amn.add((t + 1) * nb), rj1, nb));
            *y.add((t + 2) * dout + j) =
                bj0 + sj0 * (hsum(y20) + mincorr(amn.add((t + 2) * nb), rj0, nb));
            *y.add((t + 2) * dout + j + 1) =
                bj1 + sj1 * (hsum(y21) + mincorr(amn.add((t + 2) * nb), rj1, nb));
            *y.add((t + 3) * dout + j) =
                bj0 + sj0 * (hsum(y30) + mincorr(amn.add((t + 3) * nb), rj0, nb));
            *y.add((t + 3) * dout + j + 1) =
                bj1 + sj1 * (hsum(y31) + mincorr(amn.add((t + 3) * nb), rj1, nb));
            t += 4;
        }
        while t < n {
            let (cst, cmt) = (asc.add(t * nb), amn.add(t * nb));
            *y.add(t * dout + j) =
                bj0 + sj0 * dot_q8(xq.add(t * din), wj0, cst, cmt, rj0, nb);
            *y.add(t * dout + j + 1) =
                bj1 + sj1 * dot_q8(xq.add(t * din), wj1, cst, cmt, rj1, nb);
            t += 1;
        }
        j += 2;
    }
    while j < dout {
        // dout is a multiple of 16 for every registered model; kept for safety
        let wj = wp.add(j * din);
        let (sj, bj) = (*sp.add(j), *bp.add(j));
        let rj = rp.add(j * nb);
        for t in 0..n {
            *y.add(t * dout + j) = bj + sj * dot_q8(
                xq.add(t * din), wj, asc.add(t * nb), amn.add(t * nb), rj, nb);
        }
        j += 1;
    }
}

unsafe fn ln_row(row: *mut f32, g_off: usize, b_off: usize) {
    let mut m = 0.0f32;
    for d in 0..H { m += *row.add(d); }
    m /= H as f32;
    let mut v = 0.0f32;
    for d in 0..H { let z = *row.add(d) - m; v += z * z; }
    v /= H as f32;
    let inv = 1.0 / sqrtf(v + LN_EPS);
    for d in 0..H {
        *row.add(d) = (*row.add(d) - m) * inv * W[g_off + d] + W[b_off + d];
    }
}

unsafe fn add_residual_ln(res: *mut f32, g_off: usize, b_off: usize, n: usize) {
    for t in 0..n {
        let xr = res.add(t * H);
        let pr = PROJ.as_ptr().add(t * H);
        for d in 0..H { *xr.add(d) += *pr.add(d); }
        ln_row(xr, g_off, b_off);
    }
}

unsafe fn attention(n: usize) {
    let scale = 1.0 / sqrtf(DH as f32);
    for h in 0..HEADS {
        let ho = h * DH;
        for t in 0..n {
            let qp = Q.as_ptr().add(t * H + ho);
            let mut mx = f32::NEG_INFINITY;
            for s in 0..n {
                let v = dot(qp, K.as_ptr().add(s * H + ho), DH) * scale;
                SCORES[s] = v;
                if v > mx { mx = v; }
            }
            let mut sum = 0.0f32;
            for s in 0..n {
                let e = expf(SCORES[s] - mx);
                SCORES[s] = e;
                sum += e;
            }
            let inv = 1.0 / sum;
            let mut acc = [f32x4_splat(0.0); DH / 4];
            for s in 0..n {
                let p = f32x4_splat(SCORES[s] * inv);
                let vp = VA.as_ptr().add(s * H + ho);
                for j in 0..DH / 4 {
                    acc[j] = madd(p, v128_load(vp.add(4 * j) as *const v128), acc[j]);
                }
            }
            let ap = ATT.as_mut_ptr().add(t * H + ho);
            for j in 0..DH / 4 {
                v128_store(ap.add(4 * j) as *mut v128, acc[j]);
            }
        }
    }
}

#[inline]
fn gelu(x: f32) -> f32 {
    0.5 * x * (1.0 + erff(x * core::f32::consts::FRAC_1_SQRT_2))
}

struct Cur(usize);
impl Cur {
    fn take(&mut self, n: usize) -> usize { let o = self.0; self.0 += n; o }
}

#[no_mangle]
pub extern "C" fn forward(n_tokens: i32) {
    unsafe {
        let n = (n_tokens as usize).min(MAXN);
        if n == 0 {
            for d in 0..H { OUT[d] = 0.0; }
            return;
        }
        let mut c = Cur(0); // cursor into the rest region; word table is separate
        let pos = c.take(P * H);
        let typ = c.take(H);
        let eg = c.take(H);
        let eb = c.take(H);
        let wsc = if QUANT_INT8 { c.take(V) } else { 0 }; // per-vocab-row word scales

        if QUANT_INT8 {
            let word = WORD_BASE as *const i8;
            for t in 0..n {
                let id = (IDS[t] as usize).min(V - 1);
                let s = W[wsc + id];
                let wr = word.add(id * H);
                let xr = X.as_mut_ptr().add(t * H);
                for d in 0..H {
                    *xr.add(d) = s * (*wr.add(d) as f32)
                        + W[pos + (t + POS_OFFSET) * H + d]
                        + W[typ + d];
                }
                ln_row(xr, eg, eb);
            }
        } else {
            let word = WORD_BASE as *const f32;
            for t in 0..n {
                let id = (IDS[t] as usize).min(V - 1);
                let xr = X.as_mut_ptr().add(t * H);
                for d in 0..H {
                    *xr.add(d) = *word.add(id * H + d)
                        + W[pos + (t + POS_OFFSET) * H + d]
                        + W[typ + d];
                }
                ln_row(xr, eg, eb);
            }
        }

        let mut cq = Cur(0); // byte cursor into the QW int8 region
        let mut cr = Cur(0); // row cursor into RSUM (parallel to cq)
        for _l in 0..L {
            if QUANT_INT8 {
                let qs = c.take(H); let qb = c.take(H);
                let ks = c.take(H); let kb = c.take(H);
                let vs = c.take(H); let vb = c.take(H);
                let aos = c.take(H); let aob = c.take(H);
                let ag = c.take(H); let ab = c.take(H);
                let fis = c.take(I); let fib = c.take(I);
                let fos = c.take(H); let fob = c.take(H);
                let fg = c.take(H); let fb = c.take(H);
                let qw = cq.take(H * H); let kw = cq.take(H * H); let vw = cq.take(H * H);
                let aow = cq.take(H * H); let fiw = cq.take(I * H); let fow = cq.take(H * I);
                let qr = cr.take(H * (H / BQ)); let kr = cr.take(H * (H / BQ));
                let vr = cr.take(H * (H / BQ)); let aor = cr.take(H * (H / BQ));
                let fir = cr.take(I * (H / BQ)); let fo_r = cr.take(H * (I / BQ));

                quant_rows(X.as_ptr(), n, H);
                linear_q8(qw, qr, qs, qb, Q.as_mut_ptr(), n, H, H);
                linear_q8(kw, kr, ks, kb, K.as_mut_ptr(), n, H, H);
                linear_q8(vw, vr, vs, vb, VA.as_mut_ptr(), n, H, H);
                attention(n);
                quant_rows(ATT.as_ptr(), n, H);
                linear_q8(aow, aor, aos, aob, PROJ.as_mut_ptr(), n, H, H);
                add_residual_ln(X.as_mut_ptr(), ag, ab, n);

                quant_rows(X.as_ptr(), n, H);
                linear_q8(fiw, fir, fis, fib, FFN1.as_mut_ptr(), n, H, I);
                for i in 0..n * I { FFN1[i] = gelu(FFN1[i]); }
                quant_rows(FFN1.as_ptr(), n, I);
                linear_q8(fow, fo_r, fos, fob, PROJ.as_mut_ptr(), n, I, H);
                add_residual_ln(X.as_mut_ptr(), fg, fb, n);
            } else {
                let qw = c.take(H * H); let qb = c.take(H);
                let kw = c.take(H * H); let kb = c.take(H);
                let vw = c.take(H * H); let vb = c.take(H);
                let aow = c.take(H * H); let aob = c.take(H);
                let ag = c.take(H); let ab = c.take(H);
                let fiw = c.take(I * H); let fib = c.take(I);
                let fow = c.take(H * I); let fob = c.take(H);
                let fg = c.take(H); let fb = c.take(H);

                linear(X.as_ptr(), qw, qb, Q.as_mut_ptr(), n, H, H);
                linear(X.as_ptr(), kw, kb, K.as_mut_ptr(), n, H, H);
                linear(X.as_ptr(), vw, vb, VA.as_mut_ptr(), n, H, H);
                attention(n);
                linear(ATT.as_ptr(), aow, aob, PROJ.as_mut_ptr(), n, H, H);
                add_residual_ln(X.as_mut_ptr(), ag, ab, n);

                linear(X.as_ptr(), fiw, fib, FFN1.as_mut_ptr(), n, H, I);
                for i in 0..n * I { FFN1[i] = gelu(FFN1[i]); }
                linear(FFN1.as_ptr(), fow, fob, PROJ.as_mut_ptr(), n, I, H);
                add_residual_ln(X.as_mut_ptr(), fg, fb, n);
            }
        }

        // pool + L2 normalize
        for d in 0..H { OUT[d] = 0.0; }
        if POOL_CLS {
            for d in 0..H { OUT[d] = X[d]; }
        } else {
            for t in 0..n {
                for d in 0..H { OUT[d] += X[t * H + d]; }
            }
            let invn = 1.0 / n as f32;
            for d in 0..H { OUT[d] *= invn; }
        }
        let mut norm = 0.0f32;
        for d in 0..H { norm += OUT[d] * OUT[d]; }
        let inv = 1.0 / sqrtf(norm.max(1e-24));
        for d in 0..H { OUT[d] *= inv; }
    }
}
